port:  5000
markdown: kramdown
name: EcoHack Resources
url: http://rebeccawilliams.us/ecohackresources
description: "Resources for EcoHack"
encoding: utf-8
timezone: America/NewYork
navigation:
- text: Home
  url: /index.html