port:  5000
markdown: kramdown
name: EcoHack Resources

baseurl: /ecohackresources
url: /ecohackresources

description: "Resources for EcoHack"
encoding: utf-8
timezone: America/New_York
navigation:
- text: Home
  url: /index.html